### PR TITLE
Implement async

### PR DESCRIPTION
**Pull request by HeroicKatora**
This implements #70 by reworking the main crate into explicit state machines. A new crate then has the actual `async` bindings that use the state machines differently than the synchronous methods. At some point in the future these will hopefully be rewritten into proper generators with arguments instead. This PR is a work in progress.

TODO:
- [x] `OwnerSolicitor`
- [x] `access_token`
- [x] `authorization` (claimed by @Geobert)
- [x] `refresh`
- [x] `resource`

Merge overview:
 - [ ] This change has tests (remove for doc only)
 - [ ] This change has documentation
 - [x] Corresponds to issue #70 

[Contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by Geobert** [comment]
Hi,

I'm really interested in this WIP as I'm having issue combining oxide-auth and ldap3 (0.7 branch): the sync version of ldap3 is a `block_on` of the async API but as my oxide-auth usage runs in Tokio already, I can't call ldap3 in the various pieces of oxide-auth. 

I've quickly reviewed the incoming changes and I notice the absence of async for `OwnerSolicitor`. Is that intentional of just part of the todo list?

Regards,

**Comment by HeroicKatora** [comment]
Thanks for noting, it was indeed missing due to oversight. I'll add a todo list :)

**Comment by Geobert** [comment]
Is there anything I could do to help this subject? 

I'm hit by multiple issues using oxide-auth with `warp` because of the current lack of async support :) 

Most of them workaround with `tokio::task::spawn_blocking()` and using blocking version of `ldap3` but now I have an issue when `r2d2` drop the connections from Tokio's runtime and I think I won't get out of this without async support from oxide-auth so I can use async version of ldap3 :)

**Comment by Geobert** [comment]
@HeroicKatora Sorry to ping you directly, but as it's been a while since my question, maybe you didn't see it :)

**Comment by HeroicKatora** [comment]
@Geobert Sorry for not being very responsive on this issue. I don't have a lot of energy I can put into implementation here, I don't even know yet if I'm ever going to use the `async` code myself, but I'd be open to reviewing small-to-medium PR's (60-200 lines per PR would be optimal) to progress. this There are a number of things that could be done in sequence:

* Port the tests for components to support their async counter parts. This would give good insight into their current state.
* Write the `async` versions of different `Flow`'s. These should more or less be ports of their synchronous versions, calling the same underlying state machine, but do their own communication with primitives asynchronously.
* Rewrite one (or multiple) existing flows to work directly with the state machine. The raw functions in the `code_grant` would be just utilities and they can be more efficient if implemented directly.

**Comment by Geobert** [comment]
Ok, I might work on this then, we need it in our project in my company :) I need to ask permission first, I'll keep you posted!

**Comment by HeroicKatora** [comment]
That would be wonderful :+1: I just noticed, the license disclaimer in the Readme on `master` is outdated, it's MIT OR Apache-2.0 for new contributions. Please tell your legal team so they don't start with the wrong information.

**Comment by Geobert** [comment]
I'm basing my assumption on next, as it's the one we use (ring clash otherwise) :)

**Comment by Geobert** [comment]
Hi!

I am allowed to work on this by my company :D  

I began to look into the code and I noticed it is not formatted through rustfmt. Is there any reason for that?

**Comment by HeroicKatora** [comment]
That's great to hear!

>  I noticed it is not formatted through rustfmt. Is there any reason for that?

Partly because I find the tool annoying at times. I don't think it always improves consistency and at times it does the opposite (for example, wrap one branch of a `match` in blocks and not others, make long array initializers less readble, etc). However, it simply wasn't necessary and I agree with [this sentiment](https://internals.rust-lang.org/t/forced-rustfmt-is-a-roadblock-to-contributing/11913/6?u=heroickatora) to use it when the frequency of PR's goes up. You'll find many other reasons *not to* use it in the thread, it's a bit of a shame.

So feel free to do one big formatting PR first.

**Comment by HeroicKatora** [comment]
Add.: If you could, try playing around with the options of `rustfmt` to make it less aggressive and/or produce a smaller diff.

**Comment by Geobert** [comment]
I agree that sometimes I also dislike what `rustfmt` is doing, but for the sake of consistency across the Rust community, I'm complying with it :)

**Comment by Geobert** [comment]
> 
> 
> Add.: If you could, try playing around with the options of `rustfmt` to make it less aggressive and/or produce a smaller diff.

Or like you said, first PR to be just rustfmt doing its stuff? So no need to review at all.

**Comment by HeroicKatora** [comment]
Big PR and using fewer changes is not necessarily exclusive, you can commit a [global configuration file](https://github.com/rust-lang/rustfmt#configuring-rustfmt) where you could turn off or relax some of its style changes.

**Comment by Geobert** [comment]
I know I can do that, but as I said, I'm for consistency across the Rust community, but if you prefer to minimize the impact of rustfmt, I'll do that :)

**Comment by Geobert** [comment]
I'm in the middle of porting tests, starting with refresh as it's the simplest flow.

I'm using `smol` as runtime and at the moment, I've only wrapped calls to `issue()` like this: `let issued = smol::run(issuer.issue(grant)).unwrap();` in `public_client` and `private_client`.

next would be to work on the `RefreshFlow` itself and I'm wondering where should I put the async version of it.

I can either put in the current existing impl an `execute_async` or add another `impl` section in `oxide-auth-async` .

For separation of the async code, I tried to impl RefreshFlow in `oxide-auth-async` but I can't of course (defined in another crate).

So I need a trait to impl:

```rust
#[async_trait(?Send)]
pub trait AsyncExecute<E, R>
where
    E: Endpoint<R>,
    R: WebRequest,
{
    async fn execute_async(&mut self, mut request: R) -> Result<R::Response, E::Error>;
}

#[async_trait(?Send)]
impl<E, R> AsyncExecute<E, R> for RefreshFlow<E, R>
where
    E: Endpoint<R>,
    R: WebRequest,
{
    async fn execute_async(&mut self) { 
        todo!() 
    }
}
```

but I got this:
```rust
error[E0277]: the trait bound `E: oxide_auth::endpoint::Endpoint<R>` is not satisfied
  --> oxide-auth-async\src\endpoint.rs:99:12
   |
99 | impl<E, R> AsyncExecute<E, R> for RefreshFlow<E, R>
   |            ^^^^^^^^^^^^^^^^^^ the trait `oxide_auth::endpoint::Endpoint<R>` is not implemented for `E`
   | 
  ::: C:\Users\geobe\work\oxide-auth\oxide-auth\src\endpoint\refresh.rs:12:8
   |
12 |     E: Endpoint<R>,
   |        ----------- required by this bound in `oxide_auth::endpoint::refresh::RefreshFlow`
   |
help: consider further restricting this bound
   |
101|     E: Endpoint<R> + oxide_auth::endpoint::Endpoint<R>,
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The `101|     E: Endpoint<R> + oxide_auth::endpoint::Endpoint<R>,` part makes me think this might not be a good idea.

So next I'm thinking about a whole new `RefreshFlow` in `oxide-auth-async`.

What did you foreseen?

**Comment by HeroicKatora** [comment]
> EDIT: as you duplicate the Endpoint trait, I think the goal was to have a full async version, I'll with that, feel free to correct me if I'm wrong :D

Correct. Well, actually not completely but close. I did intend there to be a fully async equivalent of the `Endpoint` trait. Nevertheless, each module would have its own trait that requires the necessary primitives. Note the subtle difference: The global endpoint trait's methods return options, the local traits do not return options but do not require all primitives. Each flow (in case of `async` these can be functions and don't need to be full classes if that is simpler) would contain an adapter for the local trait that would call the methods of the global trait.

**Comment by Geobert** [comment]
> in case of `async` these can be functions and don't need to be full classes if that is simpler

I'm not sure I understand how… for the moment, I've copy pasted endpoint::refresh.rs and slap an async on execute and try to make the thing compile ^^'

**Comment by HeroicKatora** [comment]
Probably the more complicated approach to be honest. Having `pub async fn execute` is definitely what I meant but most of `endpoint::*.rs` is overengineered and _especially_ the `refresh` state machine. You'll be much happier if you start with `access_token` or `resource` instead :smiley:

**Comment by HeroicKatora** [comment]
In particular, the `refresh` state machine _borrows_ the request instead of simply cloning relevant data from it or requesting it as an input. That turned out to be a rather poor decision and very complicated to implement hence the later state machines use an alternative design. The commits descriptions ea43c9a10e3eb35f7334f1d9b69e615dd68a12f3 and c78d93d6bfa4c16522cd41f7210564b78749f6ef contain more details.

**Comment by Geobert** [comment]
Sorry to bother you, but I need help.

https://github.com/Geobert/oxide-auth/tree/async-refresh

I'm stuck on this error for a full day now :-/

And before trying harder, I wanted you to have a look at what I'm doing. Maybe I'm taking a wrong route altogether and I'm hurting my brain for nothing ^^'

Ignore the "a_" prefix, it was to make the error message clearer (I'm quite lost with multiple type with the same name ^^')

```
error[E0277]: the trait bound `(dyn a_primitives::Registrar + 'a): oxide_auth::primitives::registrar::Registrar` is 
not satisfied
   --> oxide-auth-async\src\a_frontends\simple\endpoint.rs:327:6
    |
327 | ) -> RefreshFlow<Refresh<'a>, W>
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `oxide_auth::primitives::registrar::Registrar` is not implemented for `(dyn a_primitives::Registrar + 'a)`
    | 
   ::: oxide-auth-async\src\a_endpoint\refresh.rs:15:12
    |
15  | pub struct RefreshFlow<E, R>
    |            ----------- required by a bound in this
16  | where
17  |     E: Endpoint<R>,
    |        ----------- required by this bound in `a_endpoint::refresh::RefreshFlow`
    |
    = note: required because of the requirements on the impl of `oxide_auth::primitives::registrar::Registrar` for `&'a (dyn a_primitives::Registrar + 'a)`
    = note: required because of the requirements on the impl of `a_primitives::Registrar` for `&'a (dyn a_primitives::Registrar + 'a)`
    = note: required because of the requirements on the impl of `a_frontends::simple::endpoint::OptRegistrar` for `&'a (dyn a_primitives::Registrar + 'a)`
    = note: required because of the requirements on the impl of `a_endpoint::Endpoint<W>` for `a_frontends::simple::endpoint::Generic<&'a (dyn a_primitives::Registrar + 'a), a_frontends::simple::endpoint::Vacant, &'a mut (dyn a_primitives::Issuer + 'a)>`

error[E0277]: the trait bound `(dyn a_primitives::Issuer + 'a): oxide_auth::primitives::issuer::Issuer` is not satisfied
   --> oxide-auth-async\src\a_frontends\simple\endpoint.rs:327:6
    |
327 | ) -> RefreshFlow<Refresh<'a>, W>
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `oxide_auth::primitives::issuer::Issuer` is not implemented for `(dyn a_primitives::Issuer + 'a)`
    | 
   ::: oxide-auth-async\src\a_endpoint\refresh.rs:15:12
    |
15  | pub struct RefreshFlow<E, R>
    |            ----------- required by a bound in this
16  | where
17  |     E: Endpoint<R>,
    |        ----------- required by this bound in `a_endpoint::refresh::RefreshFlow`
    |
    = note: required because of the requirements on the impl of `oxide_auth::primitives::issuer::Issuer` for `&'a mut (dyn a_primitives::Issuer + 'a)`
    = note: required because of the requirements on the impl of `a_primitives::Issuer` for `&'a mut (dyn a_primitives::Issuer + 'a)`
    = note: required because of the requirements on the impl of `a_frontends::simple::endpoint::OptIssuer` for `&'a 
mut (dyn a_primitives::Issuer + 'a)`
    = note: required because of the requirements on the impl of `a_endpoint::Endpoint<W>` for `a_frontends::simple::endpoint::Generic<&'a (dyn a_primitives::Registrar + 'a), a_frontends::simple::endpoint::Vacant, &'a mut (dyn a_primitives::Issuer + 'a)>`
```

**Comment by HeroicKatora** [comment]
> You'll be much happier if you start with access_token or resource instead [of refresh].

:sweat_smile: It was meant quite seriously. I'm somewhat sorry that you have to work with some quite raw code in the case of refresh, maybe it should first be rewritten in the style of the newer statemachines. I never planned for it to be read by another programmer in this form and felt free to experiment a bit there.

**Comment by Geobert** [comment]
> 
> 
> > You'll be much happier if you start with access_token or resource instead [of refresh].
> 
> 😅 It was meant quite seriously. I'm somewhat sorry that you have to work with some quite raw code in the case of refresh, maybe it should first be rewritten in the style of the newer statemachines. I never planned for it to be read by another programmer in this form and felt free to experiment a bit there.

No bother :D I was in the middle of it so I was thinking it will be ok, but obviously, it's not x)

I'll switch back to another flow then :)  Thank you for your answer :D

**Comment by Geobert** [comment]
Hi, today I worked on access token flow, wrote the async state machine driver  and I ended up with the same error than for refresh flow :-/

https://github.com/Geobert/oxide-auth/tree/async-access-token

```
error[E0277]: the trait bound `(dyn primitives::Registrar + 'a): oxide_auth::primitives::registrar::Registrar` is not satisfied
   --> oxide-auth-async\src\frontends\simple\endpoint.rs:336:6
    |
336 | ) -> AccessTokenFlow<AccessToken<'a>, W>
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `oxide_auth::primitives::registrar::Registrar` is not implemented for `(dyn primitives::Registrar + 'a)`
    | 
   ::: oxide-auth-async\src\endpoint\access_token.rs:27:12
    |
27  | pub struct AccessTokenFlow<E, R>
    |            --------------- required by a bound in this
28  | where
29  |     E: Endpoint<R>,
    |        ----------- required by this bound in `endpoint::access_token::AccessTokenFlow`
    |
    = note: required because of the requirements on the impl of `oxide_auth::primitives::registrar::Registrar` for `&'a (dyn primitives::Registrar + 'a)`
    = note: required because of the requirements on the impl of `primitives::Registrar` for `&'a (dyn primitives::Registrar + 'a)`
    = note: required because of the requirements on the impl of `frontends::simple::endpoint::OptRegistrar` for `&'a (dyn primitives::Registrar + 'a)`
    = note: required because of the requirements on the impl of `endpoint::Endpoint<W>` for `frontends::simple::endpoint::Generic<&'a (dyn primitives::Registrar + 'a), &'a mut (dyn primitives::Authorizer + 'a), &'a mut (dyn primitives::Issuer + 'a)>`
```

pasted only one of the error, they all revolved around the same pattern:

it wants a bound to `oxide_auth::primitives::registrar::Registrar` (or sibling trait from `oxide_auth`) which I don't understand. I never ask for such bound.

Obviously I do, but can't find where :-/

**Comment by HeroicKatora** [comment]
Can you try to split your commits more? It's very hard to review if a single +3k,-3k commit consists to one half of commented-out code, and multiple files with no change besides the line endings having been changed to Windows `\r\n`. For example, just your additions of the module `access_token` to ` oxide-auth-async/src/code_grant.rs ` would be a wonderful first commit :slightly_smiling_face:

**Comment by Geobert** [comment]
I'll do that :)  I don't understand why my files changed the EOL though :-/

**Comment by HeroicKatora** [comment]
Maybe don't port the `simple` endpoint out right? You don't _need_ it for the tests, you can always provide a local type and local impl of the `Endpoint` trait where you need an endpoint.

**Comment by Geobert** [comment]
> 
> 
> Maybe don't port the `simple` endpoint out right? You don't _need_ it for the tests, you can always provide a local type and local impl of the `Endpoint` trait where you need an endpoint.

Good idea, I was blindly pulling everything needed to keep the same code as much as possible ^^

**Comment by Geobert** [comment]
Hi, I've fixed my EOL issue, and pushed the first commit (driving the access token state machine) :) No PR yet, but if you think it's ok to merge, let me know

**Comment by HeroicKatora** [comment]
That looks good :+1: The necessity to mark the constructors public makes me wonder if these should be handled internally in the underlying state machine but that can be changed later.

**Comment by Geobert** [comment]
Ok, PR created for this small piece :) I'm trying to have the test adapted without `simple`

**Comment by Geobert** [comment]
Hi, 

If I understand properly, there's no state machine for authorization yet?

**Comment by Geobert** [comment]
> 
> 
> Hi,
> 
> If I understand properly, there's no state machine for authorization yet?

@HeroicKatora Just to be sure we're not overlapping, I'm trying to do the state machine for authorization :)

**Comment by Geobert** [comment]
What's next? I was thinking clean up warnings and fix conflict with the `next` branch

**Comment by Geobert** [comment]
I've started to port my app using `async` and it seems we need to implement `Registrar` (and probably the other primitives as well) for a couple of std types like `MutexGuard`, `Box` and so on, like you've done for the sync version of `Registrar`. Am I correct or am I missing something here?

**Comment by HeroicKatora** [comment]
@Geobert Is it possible to add a blanket impl for the async primitives based on the sync primitives? Or does that conflict with something important?

**Comment by Geobert** [comment]
> 
> 
> @Geobert Is it possible to add a blanket impl for the async primitives based on the sync primitives? Or does that conflict with something important?

Just tried to add the blanket impl, and it conflicts with the impl you put:
```rust
#[async_trait(?Send)]
impl<T> Registrar for T
where
    T: registrar::Registrar + ?Sized,
{
    async fn bound_redirect<'a>(&self, bound: ClientUrl<'a>) -> Result<BoundClient<'a>, RegistrarError> {
        registrar::Registrar::bound_redirect(self, bound)
    }

    async fn negotiate<'a>(
        &self, client: BoundClient<'a>, scope: Option<Scope>,
    ) -> Result<PreGrant, RegistrarError> {
        registrar::Registrar::negotiate(self, client, scope)
    }

    async fn check(&self, client_id: &str, passphrase: Option<&[u8]>) -> Result<(), RegistrarError> {
        registrar::Registrar::check(self, client_id, passphrase)
    }
}
```

as all the blanket impl satisfy `T: registrar::Registrar + ?Sized`

In my app, I'm trying to move everything to async, and so my registrar is implementing async version of `Registrar` and not at all the sync one. 

It's wrap into a Mutex and compiler shout at me because MutexGuard doesn't impl async::Registrar

**Comment by Geobert** [comment]
Another issue I didn't foreseen: some things need the `Send` marker now, like `code_grant::authorization::Endpoint`. Which makes me think about the implications on the interface.

Or maybe just slapping `#[async_trait(?Send)]` on the trait solves it?

**Comment by HeroicKatora** [comment]
I might have misunderstood the trait as well. The better bound could be `#[async_trait(?Sync)]`, i.e.  we surely never use the same reference to a primitive in different threads. The problem with `async_trait` is that requirements directly influence the impls. If one wants to allow _some_ primitives that are not `Send` then _none_ of the futures returned by the trait can be `Send`. Oh well, requiring `Send` is more or less standard. If it works then change the bound to `?Sync`.

**Comment by Geobert** [comment]
Ok I'll try to arrange that :) but before doing a PR on this I'd like to have the doc PR and the (to be created) rebase PR to land first :)

**Comment by Geobert** [comment]
Hm I create a branch from origin/async, then rebase next on it, but the PR says that fork/async-rebase conflict with origin/async :-/ but it can be merged into `next`…

Shall I do a merge of origin/next instead?

**Comment by HeroicKatora** [comment]
It's actually expected that a rebase of `async` onto `next` would conflict with `async`. You can open the whole thing as a new PR to `next`.

**Comment by Geobert** [comment]
> 
> 
> I might have misunderstood the trait as well. The problem with `async_trait` is that requirements directly influence the impls. If one wants to allow _some_ primitives that are not `Send` then _none_ of the futures returned by the trait can be `Send`. Oh well, requiring `Send` is more or less standard. If it works then change or remove the bound .

Removing `?Send` leads me to add `+ Send`  to `dyn Request`, which leads me to add `+Send` again to `dyn WebRequest` which lead me to be stuck on:
```
`(dyn oxide_auth::endpoint::query::QueryParameter + 'static)` cannot be shared between threads safely
```

Because of:
```rust
struct WrappedRequest<'a, R: WebRequest + Send + 'a> {
    /// Original request.
    request: PhantomData<R>,

    /// The query in the url.
    body: Cow<'a, dyn QueryParameter + 'static>,

    /// The authorization tuple
    authorization: Option<Authorization>,

    /// An error if one occurred.
    error: Option<FailParse<R::Error>>,

    /// The credentials-in-body flag from the flow.
    allow_credentials_in_body: bool,
}
```

But if I add `+Send` to `dyn QueryParameter`:
```
error[E0277]: the trait bound `(dyn oxide_auth::endpoint::query::QueryParameter + std::marker::Send + 'static): std::clone::Clone` is not satisfied
  --> oxide-auth-async\src\endpoint\access_token.rs:47:5
   |
47 |     body: Cow<'a, dyn QueryParameter + Send + 'static>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::clone::Clone` is not implemented for 
`(dyn oxide_auth::endpoint::query::QueryParameter + std::marker::Send + 'static)`
   |
   = note: required because of the requirements on the impl of `std::borrow::ToOwned` for `(dyn oxide_auth::endpoint::query::QueryParameter + std::marker::Send + 'static)`
   = note: required because it appears within the type `std::borrow::Cow<'a, (dyn oxide_auth::endpoint::query::QueryParameter + std::marker::Send + 'static)>`
   = note: only the last field of a struct may have a dynamically sized type
```

And then I'm stuck :( 🆘 

Shall we have an async version of the whole `query` module? So I can protect data with mutex and all?

**Comment by HeroicKatora** [comment]
I can close this in favor of #101 , right? If so then let's continue discussion there. Tip: You can create comment-reviews on your own PR for discussions that can later be hidden when they are resolved.

**Comment by Geobert** [comment]
> 
> 
> I can close this in favor of #101 , right? If so then let's continue discussion there. Tip: You can create comment-reviews on your own PR for discussions that can later be hidden when they are resolved.

Yes you can, thanks for the tip!

**Pull request closed without merging**
