### PR TITLE
Axum integration

### PR DESCRIPTION
**Pull request by danielalvsaaker**
Integration with the [Axum](https://github.com/tokio-rs/axum) web framework. 
 
------------------------------------

- [x] I have read the [contribution guidelines][Contributing]
 - [x] This change has documentation

I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

[Contributing]: CONTRIBUTING.md

### CODE REVIEW

**Review by HeroicKatora — APPROVED** [review]
I'll pick up the nightly CI errors, looks like the base image was renamed or I move to Github Actions anyways. This won't affect this PR.

Who's going to publish the crate?

**Comment by danielalvsaaker** [comment]
I'd be happy to do it.

**Comment by HeroicKatora** [comment]
Usually I publish the crate version from a CI-ready feature branch, then go ahead with merging. So just tell me when that's done, or if you want the merge to happen before that, it's 'just' policy afterall.

**Comment by danielalvsaaker** [comment]
Published now.

**Pull request merged**
