### PR TITLE
Split oxide-auth into crates for each integration

### PR DESCRIPTION
**Pull request by asonix**
Start splitting each webframework into a subcrate, exposing each integration through feature flags on a facade crate.

Currently features
- core crate containing the basic types and traits
- actix 0.7 integration crate
- iron 0.6 integration crate
- rocket 0.4 integration crate
- rouille 3.0 integration crate

notes
 - [x] I have read the [contribution guidelines][Contributing]
 - [x] This change has tests (remove for doc only)
 - [x] This change has documentation
 - [x] Corresponds to issue #47 

[Contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by asonix** [comment]
there's probably a lot more changes in this PR than there needed to be since my editor automatically cargo-formats each file I edit on save...

**Comment by asonix** [comment]
there's probably a lot more changes in this PR than there needed to be since my editor automatically cargo-formats each file I edit on save...

**Comment by asonix** [comment]
I think this is ready to be looked at, now

**Comment by HeroicKatora** [comment]
Just wow, thank you so much. There is already such a split in progress, see [the `next` branch](https://github.com/HeroicKatora/oxide-auth/tree/next). Can you rebase your frontend crates/implementions onto that? Examples should be placed next to their integration crates, e.g. in `oxide-auth-rouille/examples` for rouillle examples.

You seem to have put some extra work into keeping the central interface of the main crate in-tact with features, I've entertained directing users into choosing the correct frontend crate instead. The features have been a pain to work with in the past, especially since choosing two different frontends is seldomly useful but extremely hard to maintain. And the major version number would not be anywhere near as accurate as useful. So maybe `oxide-auth 0.5` should just be `oxide-auth-core` with `oxide-auth-actix` being the dependency to choose when coding for `actix`.

> there's probably a lot more changes in this PR than there needed to be since my editor automatically cargo-formats each file I edit on save...

Highly preferrably without editor autoformatting, it messes with git a log. For example `examples/iron-example/src/main.rs` is not even recognized as a moved file anymore... If it has to be, then first do all the autoformatting in one streak of commits and then the changes themselves. I've already had a hard time picking out the places where `feature` was still in use for example.

**Comment by asonix** [comment]
Changes ported over to #50

**Pull request closed without merging**
