### PR TITLE
fix: async trait impl for Extensions related stuff

### PR DESCRIPTION
**Pull request by Geobert**
This is needed to use PKCE in an async env

fixes https://github.com/HeroicKatora/oxide-auth/issues/170

### CODE REVIEW

**Comment by Geobert** [comment]
The cargo.toml is messed up (needed to remove the example as one of them needs nightly toolchain and forgot to restore them) Will do when I’m back ^^'

**Comment by Geobert** [comment]
Hi, I’m back! 

Did you manage to have a look at this?

**Comment by Geobert** [comment]
Is there anything wrong with this PR or it’s just a matter of having time to review it?

**Comment by HeroicKatora** [comment]
Just a matter of having time to review. It's good you ask since it's slightly slipped my mind :slightly_smiling_face: 
Which is to say, any external review would also be appreciated even if it's a colleague of otherwise.

**Review by HeroicKatora — APPROVED** [review]
Probably needs a new release, right?

**Comment by Geobert** [comment]
Thank you for reviewing/merging this!

Yes a release would be needed :)

**Pull request merged**
