### PR TITLE
fix doc warnings

### PR DESCRIPTION
**Pull request by Geobert**
Just fixing docs warning

I've put a couple of `#[allow(missing_doc)]` when I had nothing to say, let me know if it's an issue

### CODE REVIEW

**Comment by Geobert** [comment]
Once this is merged, I'll rebase the `async` branch over `next` one

**Comment by Geobert** [comment]
Thank you for the review, doc is done :)

**Comment by HeroicKatora** [comment]
There are still some `allow()` left. I did mean the other state machines/input/output types as well. Sorry for not being clear but I didn't want to make the review completely repetitive by slapping 'here as well' on every occurrence.

**Comment by Geobert** [comment]
> 
> 
> There are still some `allow()` left. I did mean the other state machines/input/output types as well. Sorry for not being clear but I didn't want to make the review completely repetitive by slapping 'here as well' on every occurrence.

Oh, my bad :)

**Comment by Geobert** [comment]
Done ^^

**Comment by Geobert** [comment]
thank you!

**Pull request merged**
