### PR TITLE
Remove ring from pkce and generator

### PR DESCRIPTION
**Pull request by thespooler**
This improves PR #84 by not including argonautica and only removing ring from pkce and generator.
Also includes changes discussed in #84.

[Contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by thespooler** [comment]
Also, this is a step towards #55

**Comment by Geobert** [comment]
Hi, 

is there a plan to backport the removal of ring in `0.4` branch? 

I'd like to use `oxide-auth` in a production environment but ring version pulled by `oxide-auth` 0.4.5 (through `actix-web` 0.7) is clashing with the one pulled by `warp` 0.2

**Comment by HeroicKatora** [comment]
@Geobert There are no plans. Since the replacement also changed the algorithms used this would also be a breaking change in any case, or require more work than a simple backport.

**Comment by Geobert** [comment]
Thank you for your answer!

I see. I'm looking forward to 0.5 then :D Thanks again!

**Pull request merged**
