### PR TITLE
Split ring into separate crate

### PR DESCRIPTION
**Pull request by asonix**
This change splits ring, and types based on ring-backed types, into another crate to avoid a hard dependency on Ring. A lot of the concrete implementation does depend on ring, so a good deal of tests have moved over into the ring crate, also

 - [x] I have read the [contribution guidelines][Contributing]
 - [x] This change has tests (remove for doc only)
 - [x] This change has documentation
 - [x] Corresponds to issue #55 

[Contributing]: CONTRIBUTING.md

### CODE REVIEW

**Comment by HeroicKatora** [comment]
I've been a bit conflicted regarding these changes. After a bit of consideration I think this is missing the tree for the forest. Since this moves *all* provided implementations of some traits to the `-ring` trait it doesn't actually help avoid `ring` in the depency tree unless you were to only use custom implementations anyways. But then a simple feature switch to enable the `ring` implementations would be potent enough?

There are a number of points I'd want to see addressed individually:
* Some changes to the interface are also done here. What is the reasoning behind them? If they are necessary then they should be done regardless of the split and separately from it.
* Tests are also moved (since no implementations of some primitives exist). This *drastically* reduces coverage.
* One positive thing, I'm much more open-minded towards replacing `ring` with a combination of other crypto library if the `ring` implementations are kept available somewhere else. Purely adding the `-ring` crate for now also makes it easier to review.
* The `-ring` crate has no problem comitting to a `ring` depency in its interface. That means some utility constructors from `hmac::Key` that were avoided could be added back?

**Comment by asonix** [comment]
I do have an additional branch which implements the extent of the `-ring` crate with rustcrypto libs. It make additional changes to the API, specifically requiring that `registrar` be mutable.

I think my reasoning for changing the API in this PR was to prepare a bit for that, but you're right that this PR specifically doesn't (and shouldn't) depend on the API change.

**Comment by asonix** [comment]
And also, doesn't it make sense that the tests would test the implementation, rather than the interface? In a statically-typed language like Rust, the interface is well-defined just by existing, is it not?

I'd also argue that test coverage has not reduced, since the same code is being tested with the same tests, they're just somewhere else in the file structure

**Comment by asonix** [comment]
Here's the actual changes for adding rustcrypto https://github.com/Aardwolf-Social/oxide-auth/pull/1

it's likely that things could be done _better_, since some types are duplicated across -ring and -rustcrypto that could be defined in the base crate with a generic

**Comment by HeroicKatora** [comment]
> It makes additional changes to the API, specifically requiring that registrar be mutable.

Yes I noted but why?

**Comment by HeroicKatora** [comment]
To be more precise, what are you trying to achieve with the API change? Why should `check` have to mutate the data structure for example?

**Comment by HeroicKatora** [comment]
> And also, doesn't it make sense that the tests would test the implementation, rather than the interface? In a statically-typed language like Rust, the interface is well-defined just by existing, is it not?

> I'd also argue that test coverage has not reduced, since the same code is being tested with the same tests, they're just somewhere else in the file structure.

They are in another crate and the new structure and removal of the default features make it impossible to test the interface of `oxide-auth` alone. I find that extremely irritating. In that case every addition or change in `oxide-auth` needs to be immediately adapted for in the `-ring` crate to allow it to be tested. That's creates a hard dependency that (I think) shouldn't exist between these separate crates even though they share the same workspace. And release are no longer self-contained. Usually I can download a crate's published files to also run its testsuite.

**Comment by HeroicKatora** [comment]
Note: (Integration) tests use the `[dev-dependencies]` so with a dependency cycle this may work without moving the tests themselves. At least that makes the review of the changes easier. I'm still not sure how well the workspace can cope with `[dev-dependencies]` requiring a version different from the one that exists locally (on the offchance of this being required for some reason)?

**Comment by asonix** [comment]
The reason for making some of these methods mutable is due to the RustCrypto and Rand implementations' reliance on having mutability. For example, things implementing rand's `Rng` trait (e.g. StdRng) need to be mutable to use `try_fill` when filling a buffer. Things implementing RustCrypto's Digest trait (e.g. Sha256) need to be mutable to hash and verify.

**Comment by asonix** [comment]
Not _all_ implementations of these traits need mutability (ring didn't, obviously), but some implementations might.

**Comment by HeroicKatora** [comment]
> The reason for making some of these methods mutable is due to the RustCrypto and Rand implementations' reliance on having mutability. For example, things implementing rand's Rng trait (e.g. StdRng) need to be mutable to use try_fill when filling a buffer. Things implementing RustCrypto's Digest trait (e.g. Sha256) need to be mutable to hash and verify.

For the case of `Rng` use *internal* mutability. That's precisely what it was made for. Most rng implementations will still not require it because they are in thread local storage and so fully `Sync` or rather they have their own mutability. I don't get how `Digest` influence this at all since it should just be on the stack during the evaluation of `check` but not have any other state.

**Comment by asonix** [comment]
In the case of the RustCrypto implementation of `Assertion`, it carries around a `Hmac<Sha256>` internally, which must be mutable to sign data.
```rust
self.secret.input(&to_sign);
self.secret.result_reset()
```
This could be avoided by just using `Hmac::<Sha256>::new_varkey(key_bytes)` each time `signature` is called, but that seems like not a great idea (the ring implementation carries the SigningKey type around).

**Comment by asonix** [comment]
Now that I look at it again, I'm not convinced PasswordPolicy's `store` method needs to be mutable, which would also mean `check` would not need to be mutable. Maybe an earlier iteration of the code needed this, but that is no longer true.

**Comment by asonix** [comment]
I think I was hesitant to clone the Hmac because I've been burned by cloning StdRng in the past, but you're right that Hmac itself is likely safe to clone, since it's deterministic and doesn't contain randomness.

**Comment by asonix** [comment]
I think what I will do this evening is I will re-create this PR without changes to the interface, and maybe a circular dev-dependency to leave more of the tests in the primary crate.

**Pull request closed without merging**
