### PR TITLE
fix: Credentials being overriden

### PR DESCRIPTION
**Pull request by Geobert**
This fixes

 - [x] I have read the [contribution guidelines][Contributing]
 - [ ] This change has tests (remove for doc only)
 - [x] Corresponds to issue (#89)

I'm not sure on how to stub to write a test. But the change seems trivial.

### CODE REVIEW

**Comment by HeroicKatora** [comment]
The change is anything but trivial, this modifies authentication and _must_ have tests for the bug fix. One thing that previously was not allowed, and now is but shouldn't be, is to have both an authentication in the body and an authorization header. This is bad, I remember actively testing this and currently worried why the PR doesn't fail [this test](https://github.com/HeroicKatora/oxide-auth/blob/next/oxide-auth/src/endpoint/tests/authorization.rs#L486).

**Comment by Geobert** [comment]
> 
> 
> The change is anything but trivial, this modifies authentication and _must_ have tests for the bug fix. One thing that previously was not allowed, and now is but shouldn't be, is to have both an authentication in the body and an authorization header. This is bad, I remember actively testing this and currently worried why the PR doesn't fail [this test](https://github.com/HeroicKatora/oxide-auth/blob/next/oxide-auth/src/endpoint/tests/authorization.rs#L486), and why it fails some other unrelated test now whereas the branch came back clean...

Yes, Just seen that, looking into it :)

**Comment by HeroicKatora** [comment]
>EDIT: your link goes nowhere, there's no line 486

Oops, wrong file :smile:

**Comment by Geobert** [comment]
So here are the steps I'm taking:
- look why private_duplicate_authentication doesn't fail and make it fail
- write a test for my bug
- fix the bug

Are you OK with that?

**Comment by HeroicKatora** [comment]
That seems fine :+1:

**Comment by Geobert** [comment]
actually the test doesn't fail and it's right to not to: the Duplicate is properly caught, I understand better what you mean.

(English is not my native language and it's Friday afternoon here ^^')

**Comment by Geobert** [comment]
Oh, maybe there's no bug: 
How should we react if there's client_id in the body (but no client_secret)?

**Pull request closed without merging**
